services:

  database:
    container_name: rm-database
    image: postgres:14.1
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: "/var/lib/postgresql/data/pgdata"

  migration:
    container_name: rm-migration
    image: flyway/flyway:8.4.4
    command: >
      -url=jdbc:postgresql://${POSTGRES_HOST}:5432/${POSTGRES_DB}
      -user=${POSTGRES_USER}
      -password=${POSTGRES_PASSWORD}
      -connectRetries=10 
      -connectRetriesInterval=5 
      migrate
    depends_on:
      - database

  server:
    container_name: rm-server
    image: openjdk:17-alpine
    ports:
      - 7080:8080
    command: ["java", "-jar", "/var/roof-mates-0.0.1-all.jar"]
    depends_on:
      - migration
    links:
      - database